function change_gene_symbols_NonNeuron(MarkerSize, FontSize, MultiCol)
% ChangeGeneSymbols(MarkerSize, FontSize, nPerCol);
%
% changes gene symbols so in situ plots look nice. 
% MarkerSize defaults to 6 - if 0, won't change existing sizes
%
% FontSize is font size for legend
%
% nPerCol says how many legend entries per column (0 for one-column)
% 
% Kenneth D. Harris, 29/3/17
% GPL 3.0 https://www.gnu.org/licenses/gpl-3.0.en.html
 
if nargin<1 || isempty(MarkerSize)
    MarkerSize = 6;
end
MarkerSize = 6;
if nargin<2 || isempty(FontSize)
    FontSize = 5;
end

if nargin<3
    MultiCol = 49;
end

%Want 34 distinguishable RGB colors, that will show up on black[0,0,0]
%and that are not grey [0.0667,0.0667,0.0667] as these are neurons.
BackgroundColors = [0,0,0;0.0667,0.0667,0.0667;1,1,1];
Colors = distinguishable_colors(33,BackgroundColors);

% Colors based on Class Assignments
CHOR = Colors(1,:);
VLMC = Colors(2,:);
OEC = Colors(3,:);
PER = Colors(4,:);
MOL = [1,1,1];
EPSC = Colors(6,:);
ACMB = Colors(7,:);
ABC = Colors(8,:);
DETPH = Colors(9,:);
PVM = Colors(10,:);
VECA = Colors(11,:);
MGL = Colors(12,:);
MFOL = Colors(13,:);
VSMCA = Colors(14,:);
VECV = Colors(15,:);
MSN = Colors(16,:);
NFOL = Colors(17,:);
ACOB = Colors(18,:);
HBGLU = Colors(19,:);
HBCHO = Colors(20,:);
DGNBL = Colors(21,:);
OBNBL = Colors(22,:);
ACBG = Colors(23,:);
HBSER = Colors(24,:);
CBPC = Colors(25,:);
EPEN = Colors(26,:);
SATG = Colors(27,:);
COP = Colors(28,:);
SEPNBL = Colors(29,:);
MBDOP = Colors(30,:);
SZNBL = Colors(31,:);
HBINH = Colors(32,:);
DECHO = Colors(33,:);
ACTE = Colors(5,:);


% All symbols: +o*.xsd^v<>ph - have them in that order to not get confused
New_symbols = {...
    'Mgp', ABC, '+'; ...
    'Rbp1', ABC, 'o'; ...
    'Fn1', ABC, '*'; ...
    'Igfbp6', ABC, '.'; ...
    'Slc1a3', ACBG, '+'; ...
    'Gfap', ACMB, '+'; ...
    'Aqp4', ACMB, 'o'; ...
    'Slc6a11', ACOB, '+'; ...
    'Slc1a2', ACTE, '+'; ...
    'Aldoc', ACTE, 'o'; ...
    'Car8', CBPC, 's'; ...
    'Ttr', CHOR, '+'; ...
    'Enpp2', CHOR, '<'; ...
    '1500015O10Rik', CHOR, '*'; ...
    'Fxyd1', CHOR, 'v'; ...
    'Sostdc1', CHOR, 'x'; ...
    'Cd9', COP, 'd'; ...
    'Frmd4a', COP, '^'; ...
    'Gpr17', COP, 'v'; ...
    'Lhx8', DECHO, 'p'; ...
    'Pde6g', DETPH, '*'; ...
    'Sag', DETPH, '.'; ...
    'Gnb3', DETPH, 'x'; ...
    'Igfbpl1', DGNBL, 's'; ...
    '1110017D15Rik', EPEN, '+'; ...
    'Ccdc153', EPEN, 'o'; ...
    'Tmem212', EPEN, '*'; ...
    'Foxj1', EPEN, '.'; ...
    'Rarres2', EPEN, 'x'; ...
    'Dbi', EPSC, 's'; ...
    'Fos', EPSC, 'd'; ...
    'Ifitm3', EPSC, '^'; ...
    'Rsph1', EPSC, '*'; ...
    'Jun', EPSC, '+'; ...
    'Mia', EPSC, '<'; ...
    'Syt4', HBCHO, 'x'; ...
    'Vat1l', HBCHO, 's'; ...
    'Efr3a', HBGLU, '+'; ...
    'Slc17a6', HBGLU, 'o'; ...
    'Snap25', HBGLU, '*'; ...
    'Cabp7', HBGLU, '.'; ...
    'Gls', HBGLU, 'x'; ...
    'Irs4', HBINH, 'v'; ...
    'Peg3', HBSER, '^'; ...
    'Cntn1', HBSER, '<'; ...
    'Hs6st2', HBSER, 'p'; ...
    'En1', MBDOP, 'x'; ...
    'Mag', MFOL, '+'; ...
    'Mobp', MFOL, 'o'; ...
    'Opalin', MFOL, '*'; ...
    'Tspan2', MFOL, '.'; ...
    'Grb14', MFOL, 'x'; ...
    'Olig1', MFOL, 's'; ...
    'Tmem141', MFOL, 'd'; ...
    'Pdlim2', MFOL, '^'; ...
    'Cd81', MFOL, '<'; ...
    'Hexb', MGL, '+'; ...
    'Ctss', MGL, 'o'; ...
    'C1qa', MGL, '*'; ...
    'P2ry12', MGL, '.'; ...
    'C1qb', MGL, 'x'; ...
    'Ccl4', MGL, 'v'; ...
    'Trf', MOL, '+'; ...
    'Mog', MOL, 'o'; ...
    'Apod', MOL, '*'; ...
    'S100b', MOL, '.'; ...
    'Gsn', MOL, 'p'; ...
    'Gltp', MOL, 's'; ...
    'Ppp1r14a', MOL, 'd'; ...
    'Car2', MOL, '^'; ...
    'Fa2h', MOL, 'v'; ...
    'Klk6', MOL, '>'; ...
    'Sepp1', MOL, 'h'; ...
    'Pllp', MOL, 'h'; ...
    'Cdkn1c', MOL, 'h'; ...
    'Gjb1', MOL, '<'; ...
    'Plp1', MOL, 'x'; ...
    'Mal', MOL, 'h'; ...
    'Ppp1r1b', MSN, 's'; ...
    'Arpp21', MSN, 'd'; ...
    'Pde10a', MSN, '^'; ...
    'Nfasc', NFOL, '+'; ...
    'Sirt2', NFOL, 'o'; ...
    'Marcks', NFOL, '*'; ...
    'Rras2', NFOL, '.'; ...
    'Arpc1b', NFOL, 'x'; ...
    'Tsc22d4', NFOL, 's'; ...
    'Qk', NFOL, 'd'; ...
    'Gng12', NFOL, '^'; ...
    'Gm15440', NFOL, '<'; ...
    'Doc2g', OBNBL, '.'; ...
    'Cdhr1', OBNBL, 'x'; ...
    'Nmb', OBNBL, 's'; ...
    'Fabp7', OEC, 's'; ...
    'Cldn5', PER, '+'; ...
    'Igfbp7', PER, 'o'; ...
    'Vtn', PER, '*'; ...
    'Sparc', PER, '.'; ...
    'Ctla2a', PER, 'x'; ...
    'Higd1b', PER, 's'; ...
    'Pglyrp1', PER, 'd'; ...
    'Myl12a', PER, '^'; ...
    'Gng11', PER, 'v'; ...
    'Serpinh1', PER, '>'; ...
    'Rhoc', PER, 'h'; ...
    'Col4a1', PER, '<'; ...
    'Lyz2', PVM, '+'; ...
    'Pf4', PVM, 'o'; ...
    'C1qc', PVM, '*'; ...
    'Fcer1g', PVM, '.'; ...
    'Tyrobp', PVM, 'x'; ...
    'Rgcc', SATG, '+'; ...
    'Sfrp5', SATG, 'o'; ...
    'Fbln5', SATG, '*'; ...
    'Fbln2', SATG, '>'; ...
    'Ube2c', SATG, 'x'; ...
    'Vim', SATG, 's'; ...
    'A230065H16Rik', SEPNBL, 'h'; ...
    'Hmgb2', SZNBL, 's'; ...
    'Rgs5', VECA, 'x'; ...
    'Flt1', VECA, 'v'; ...
    'Igf2', VECA, '+'; ...
    'Epas1', VECA, 'o'; ...
    'Bsg', VECV, '+'; ...
    'Itm2a', VECV, 'o'; ...
    'Ly6c1', VECV, '*'; ...
    'Car4', VECV, '<'; ...
    'Pltp', VECV, 'x'; ...
    'Ptgds', VLMC, 's'; ...
    'Igfbp2', VLMC, '+'; ...
    'Dcn', VLMC, 'o'; ...
    'Nupr1', VLMC, '*'; ...
    'Crip1', VSMCA, '+'; ...
    'Acta2', VSMCA, 'o'; ...
    'Myl9', VSMCA, '*'; ...
    'Tagln', VSMCA, '.'; ...   
};

% delete any existing legend
fc = get(gcf, 'Children');
for i=1:length(fc)
    if strcmp(get(fc(i), 'UserData'), 'key')
        delete(fc(i));
    end
end

MainAxes = gca;

n =  size(New_symbols,1);

gc = get(MainAxes, 'children');
MyChildren = [];
for i=1:length(gc)
    if (strcmp(gc(i).Type, 'line') || strcmp(gc(i).Type, 'scatter')) ...
            && ~isempty(gc(i).DisplayName)
        MyChildren = [MyChildren; i];
    end
end
DisplayNames = {gc(MyChildren).DisplayName};
% get first word of display name as gene
GeneNames = cell(size(DisplayNames));
for i=1:length(DisplayNames)
    GeneNames{i} = strtok(DisplayNames{i});
end
    
clear h s;
j=1;
Present = [];
for i=1:n
    MyGeneName = New_symbols{i,1};
    l = find(strcmp(MyGeneName, GeneNames));
    if ~isempty(l)
        h(j) = gc(MyChildren(l));
		if strcmp(h(j).Type, 'line')
			set(h(j), 'Color', New_symbols{i,2});
        elseif strcmp(h(j).Type, 'scatter')
			set(h(j), 'CData', New_symbols{i,2});
		end
        set(h(j), 'Marker', New_symbols{i,3});

        if MarkerSize>0
			if strcmp(gc(l).Type, 'line')
				set(h(j), 'MarkerSize', MarkerSize);
			elseif strcmp(gc(l).Type, 'scatter')
				set(h(j), 'SizeData', MarkerSize);
			end
        end
        Present(j) = i;
        j=j+1;
    end
end

other_h = setdiff(gc(MyChildren), h);
other_symbols = {other_h.DisplayName};

all_h = [h(:); other_h(:)];
all_sym = {New_symbols{Present,1}, other_symbols{:}};

% lh = legend([h(:); other_h(:)], ...
%     {New_symbols{s,1}, other_symbols{:}}, ...
%     'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
% set(lh, 'color', 'k');
% 
% return;

if MultiCol==0
    lh = legend(all_h, all_sym, 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
    set(lh, 'color', 'k');
else
    ah = axes('Position', [.925 .13 .05 .8]);
    set(ah, 'color', 'k'); cla; hold on; box off
    set(ah, 'UserData', 'key');
    for j=1:length(Present)
        i = Present(j);
        plot(ceil(j/MultiCol)+.1, mod(j-1,MultiCol), New_symbols{i,3}, 'Color', New_symbols{i,2});
        text(ceil(j/MultiCol)+.3, mod(j-1,MultiCol), New_symbols{i,1}, 'color', 'w', 'fontsize', FontSize);
    end
    if ~isempty(setdiff(GeneNames,New_symbols(:,1)))
        j=j+1;
        plot(ceil(j/MultiCol)+.1, mod(j-1,MultiCol), '.', 'Color', hsv2rgb([0,0,0.5]));
        text(ceil(j/MultiCol)+.3, mod(j-1,MultiCol), 'Neuron', 'color', 'w', 'fontsize', FontSize);
    end
    ylim([-1 MultiCol]);
    set(ah, 'xtick', []);
    set(ah, 'ytick', []);
    set(ah, 'ydir', 'reverse');
end
%     for c=1:nCols
%         rr=((c-1)*50 + 1):min(c*50, length(all_h));
%         if c==1
%             ah(c) = gca;
%             lh(c) = legend(all_h(rr), all_sym(rr), 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize, 'location', 'east');
%             set(lh(c), 'color', 'k');
%             pos(c,:) = get(lh(c), 'position');
%         else
%             ah(c) = axes('position',get(gca,'position'), 'visible','off');
%             lh(c) = legend(ah(c), all_h(rr), all_sym(rr), 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize, 'location', 'east');
%             set(lh(c), 'position', pos(c-1,:) + [1.1 0 0 0]*pos(c-1,3));
%             uistack(lh(c), 'top');
%         end
%     end
%     axes(ah(1));
    
%    error('multicolumn not done yet!');
% end
%     for i=1:nCols
%         first = 1+(i-1)*nCols;
%         last = min(i*nCols,length(all_h));
%         lh = legend(all_h(first:last), ...
%             all_sym{first:last});%, ...
%             %'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
%         set(lh, 'color', 'k');
%     end
set(gcf, 'color', 'k');
set(gcf, 'InvertHardcopy', 'off');
    
axes(MainAxes)
uistack(ah, 'top');

end