function change_gene_symbols_wb(MarkerSize, FontSize, MultiCol)
% ChangeGeneSymbols(MarkerSize, FontSize, nPerCol);
%
% changes gene symbols so in situ plots look nice. 
% MarkerSize defaults to 6 - if 0, won't change existing sizes
%
% FontSize is font size for legend
%
% nPerCol says how many legend entries per column (0 for one-column)
% 
% Kenneth D. Harris, 29/3/17
% GPL 3.0 https://www.gnu.org/licenses/gpl-3.0.en.html
 
if nargin<1 || isempty(MarkerSize)
    MarkerSize = 6;
end

if nargin<2 || isempty(FontSize)
    FontSize = 5;
end

if nargin<3
    MultiCol = 49;
end


% colors
Astrocytes = hsv2rgb([0 1 1]); % red
Ependymal =  hsv2rgb([1/6 1 1]); % yellow
Neurons =    hsv2rgb([2/6 1 1]); % green
Immune =     hsv2rgb([3/6 1 1]); % cyan
Oligos =     hsv2rgb([4/6 1 1]); % blue
Vascular =   hsv2rgb([5/6 1 1]); % magenta

Neurons13 = Neurons;
Neurons12 = Neurons;
Neurons11 = Neurons;
Neurons10 = Neurons;
Neurons9 = Neurons;
Neurons8 = Neurons;
Neurons7 = Neurons;
Neurons6 = Neurons;
Neurons5 = Neurons;
Neurons4 = Neurons;
Neurons3 = Neurons;
Neurons2 = Neurons;
Neurons1 = Neurons;

Astrocytes1 = Astrocytes;
Oligos1 =     Oligos;
Immune1 =     Immune;
Ependymal1 =  Ependymal;
Ependymal2 =  Ependymal;
Vascular1 =   Vascular;
Vascular2 =   Vascular;

% All symbols: +o*.xsd^v<>ph - have them in that order to not get confused
New_symbols = {...
    
'1500015O10Rik',	Ependymal,	'*'; ...
'2900079G21Rik',	Neurons,	'*'; ...
'6330403K07Rik',	Neurons,	'.'; ...
'A230065H16Rik',	Neurons,	'+'; ...
'Abi3bp',	Neurons,	'x'; ...
'Agrp',	Neurons,	'o'; ...
'Apoe',	Immune,	'*'; ...
'Aqp4',	Astrocytes,	'*'; ...
'Arpp21',	Neurons,	's'; ...
'Asb4',	Neurons,	'd'; ...
'Asic2',	Neurons,	'>'; ...
'Atp1a2',	Astrocytes,	'.'; ...
'Atp1a3',	Neurons,	'v'; ...
'Atp1b1',	Neurons,	'<'; ...
'Avp',	Neurons,	'^'; ...
'Bcl11a',	Neurons,	'p'; ...
'Bex1',	Neurons,	'h'; ...
'Bok',	Vascular,	'*'; ...
'C1ql1',	Oligos,	'*'; ...
'C1ql3',	Neurons1,	'*'; ...
'Cabp7',	Neurons1,	'.'; ...
'Cadm1',	Neurons1,	'+'; ...
'Calca',	Neurons1,	'x'; ...
'Calm2',	Neurons1,	'o'; ...
'Caly',	Neurons1,	's'; ...
'Camk2n1',	Neurons1,	'd'; ...
'Camk4',	Neurons1,	'>'; ...
'Camkv',	Neurons1,	'v'; ...
'Cartpt',	Neurons1,	'<'; ...
'Cbln1',	Neurons1,	'^'; ...
'Ccnd2',	Ependymal,	'.'; ...
'Cd24a',	Neurons1,	'p'; ...
'Cdhr1',	Neurons1,	'h'; ...
'Celf2',	Neurons2,	'*'; ...
'Chd3os',	Neurons2,	'.'; ...
'Ckb',	Astrocytes,	'+'; ...
'Cldn5',	Vascular,	'.'; ...
'Cnih2',	Neurons2,	'+'; ...
'Cpe',	Astrocytes,	'x'; ...
'Cplx1',	Neurons2,	'x'; ...
'Cpne4',	Neurons2,	'o'; ...
'Crabp1',	Neurons2,	's'; ...
'Cspg5',	Astrocytes,	'o'; ...
'Ctgf',	Vascular,	'+'; ...
'Ctxn3',	Neurons2,	'd'; ...
'Dbi',	Ependymal,	'+'; ...
'Dcn',	Vascular,	'x'; ...
'Ddn',	Neurons2,	'>'; ...
'Diablo',	Neurons2,	'v'; ...
'Dlk1',	Neurons2,	'<'; ...
'Dlx1',	Neurons2,	'^'; ...
'Dlx2',	Neurons2,	'p'; ...
'Dlx6os1',	Neurons2,	'h'; ...
'Dmkn',	Ependymal,	'x'; ...
'Doc2g',	Neurons3,	'*'; ...
'Drd1',	Ependymal,	'o'; ...
'Ebf1',	Vascular,	'o'; ...
'Ecel1',	Neurons3,	'.'; ...
'Etv1',	Oligos,	'.'; ...
'Fabp7',	Astrocytes,	's'; ...
'Fam216b',	Ependymal,	's'; ...
'Fgf13',	Neurons3,	'+'; ...
'Fkbp1b',	Neurons3,	'x'; ...
'Fndc5',	Neurons3,	'o'; ...
'Foxp2',	Neurons3,	's'; ...
'Fth1',	Oligos,	'+'; ...
'Fxyd2',	Neurons3,	'd'; ...
'Fxyd6',	Neurons3,	'>'; ...
'Fxyd7',	Neurons3,	'v'; ...
'Gad2',	Neurons3,	'<'; ...
'Gadd45g',	Ependymal,	'd'; ...
'Gal',	Neurons3,	'^'; ...
'Gap43',	Neurons3,	'p'; ...
'Gata2',	Vascular,	's'; ...
'Gfap',	Astrocytes,	'd'; ...
'Gfra3',	Neurons3,	'h'; ...
'Gm17750',	Ependymal,	'>'; ...
'Gm2694',	Neurons4,	'*'; ...
'Gm27199',	Neurons4,	'.'; ...
'Gm3764',	Astrocytes,	'>'; ...
'Gm42418',	Ependymal,	'v'; ...
'Gm5741',	Neurons4,	'+'; ...
'Gnrh1',	Neurons4,	'x'; ...
'Gpm6a',	Neurons4,	'o'; ...
'Gpr88',	Neurons4,	's'; ...
'Gria2',	Neurons4,	'd'; ...
'Grin2a',	Neurons4,	'>'; ...
'Grin2b',	Neurons4,	'v'; ...
'H3f3a',	Vascular,	'd'; ...
'H3f3b',	Vascular,	'>'; ...
'Hcn1',	Neurons4,	'<'; ...
'Hoxa5',	Neurons4,	'^'; ...
'Hoxa7',	Ependymal,	'<'; ...
'Hoxa9',	Ependymal,	'^'; ...
'Hoxb5',	Neurons4,	'p'; ...
'Hoxb6',	Neurons4,	'h'; ...
'Hoxb7',	Neurons5,	'*'; ...
'Hoxb8',	Neurons5,	'.'; ...
'Hoxb9',	Neurons5,	'+'; ...
'Hoxc10',	Ependymal,	'p'; ...
'Hoxc8',	Ependymal,	'h'; ...
'Hpca',	Neurons5,	'x'; ...
'Hpcal1',	Neurons5,	'o'; ...
'Htr1f',	Neurons5,	's'; ...
'Igf1',	Vascular,	'v'; ...
'Igfbp2',	Ependymal1,	'*'; ...
'Igfbp4',	Vascular,	'<'; ...
'Igfbp6',	Vascular,	'^'; ...
'Igfbpl1',	Neurons5,	'd'; ...
'Impact',	Neurons5,	'>'; ...
'Isl1',	Neurons5,	'v'; ...
'Itm2b',	Immune,	'.'; ...
'Junb',	Immune,	'+'; ...
'Kcnc1',	Neurons5,	'<'; ...
'Kcnh3',	Neurons5,	'^'; ...
'Kcnip2',	Neurons5,	'p'; ...
'Lbx1',	Neurons5,	'h'; ...
'Ldhb',	Neurons6,	'*'; ...
'Lhx1os',	Neurons6,	'.'; ...
'Lhx2',	Astrocytes,	'v'; ...
'Lix1',	Neurons6,	'+'; ...
'Lpl',	Vascular,	'p'; ...
'Lsamp',	Neurons6,	'x'; ...
'Ly6g6e',	Neurons6,	'o'; ...
'Ly6h',	Neurons6,	's'; ...
'Malat1',	Oligos,	'x'; ...
'Marcks',	Oligos,	'o'; ...
'Matn4',	Oligos,	's'; ...
'Mbp',	Oligos,	'd'; ...
'Mef2c',	Neurons6,	'd'; ...
'Meg3',	Neurons6,	'>'; ...
'Meis2',	Neurons6,	'v'; ...
'Mgp',	Vascular,	'h'; ...
'Mlc1',	Ependymal1,	'.'; ...
'Mobp',	Oligos,	'>'; ...
'Mpz',	Neurons6,	'<'; ...
'Msx1',	Ependymal1,	'+'; ...
'Mt1',	Astrocytes,	'<'; ...
'Mt3',	Ependymal1,	'x'; ...
'mt-Atp6',	Neurons6,	'^'; ...
'mt-Co3',	Neurons6,	'p'; ...
'mt-Cytb',	Ependymal1,	'o'; ...
'mt-Nd1',	Neurons6,	'h'; ...
'Myl1',	Neurons7,	'*'; ...
'Myl4',	Vascular1,	'*'; ...
'Myl9',	Vascular1,	'.'; ...
'Nap1l5',	Neurons7,	'.'; ...
'Ndufa4',	Neurons7,	'+'; ...
'Ndufa4l2',	Vascular1,	'+'; ...
'Nefl',	Neurons7,	'x'; ...
'Nefm',	Neurons7,	'o'; ...
'Nek7',	Neurons7,	's'; ...
'Neurod1',	Neurons7,	'd'; ...
'Neurod2',	Neurons7,	'>'; ...
'Nfib',	Ependymal1,	's'; ...
'Nfix',	Ependymal1,	'd'; ...
'Ngfr',	Neurons7,	'v'; ...
'Nnat',	Ependymal1,	'>'; ...
'Nppb',	Neurons7,	'<'; ...
'Nppc',	Neurons7,	'^'; ...
'Nptx1',	Neurons7,	'p'; ...
'Nrgn',	Neurons7,	'h'; ...
'Nrsn1',	Neurons8,	'*'; ...
'Nrxn1',	Neurons8,	'.'; ...
'Nrxn3',	Neurons8,	'+'; ...
'Ntn1',	Vascular1,	'x'; ...
'Nts',	Neurons8,	'x'; ...
'Ntsr2',	Astrocytes,	'^'; ...
'Olfm1',	Neurons8,	'o'; ...
'Olig1',	Oligos,	'v'; ...
'Olig2',	Oligos,	'<'; ...
'Opcml',	Neurons8,	's'; ...
'Ostf1',	Vascular1,	'o'; ...
'Otp',	Neurons8,	'd'; ...
'Oxt',	Neurons8,	'>'; ...
'Pantr1',	Astrocytes,	'p'; ...
'Pax6',	Ependymal1,	'v'; ...
'Pcdh7',	Oligos,	'^'; ...
'Pcdh8',	Neurons8,	'v'; ...
'Pcp2',	Neurons8,	'<'; ...
'Pcp4l1',	Ependymal1,	'<'; ...
'Pde10a',	Neurons8,	'^'; ...
'Pdgfra',	Vascular1,	's'; ...
'Pdyn',	Neurons8,	'p'; ...
'Pdzk1ip1',	Vascular1,	'd'; ...
'Pgam2',	Neurons8,	'h'; ...
'Pkib',	Neurons9,	'*'; ...
'Pla2g5',	Ependymal1,	'^'; ...
'Plcd4',	Ependymal1,	'p'; ...
'Pmch',	Neurons9,	'.'; ...
'Postn',	Vascular1,	'>'; ...
'Ppp1r1b',	Ependymal1,	'h'; ...
'Ppp3ca',	Neurons9,	'+'; ...
'Prkcd',	Neurons9,	'x'; ...
'Prok2',	Neurons9,	'o'; ...
'Ptgds',	Vascular1,	'v'; ...
'Ptma',	Vascular1,	'<'; ...
'Ptn',	Vascular1,	'^'; ...
'Pura',	Neurons9,	's'; ...
'Ramp1',	Ependymal2,	'*'; ...
'Ramp3',	Neurons9,	'd'; ...
'Rarres1',	Neurons9,	'>'; ...
'Rbfox1',	Neurons9,	'v'; ...
'Rbp4',	Ependymal2,	'.'; ...
'Resp18',	Neurons9,	'<'; ...
'Rgs5',	Vascular1,	'p'; ...
'Rln3',	Neurons9,	'^'; ...
'Rora',	Neurons9,	'p'; ...
'Rpl26',	Neurons9,	'h'; ...
'Rprm',	Neurons10,	'*'; ...
'Rprml',	Neurons10,	'.'; ...
'Rps2',	Neurons10,	'+'; ...
'Rsrp1',	Neurons10,	'x'; ...
'S100a6',	Neurons10,	'o'; ...
'Sall3',	Ependymal2,	'+'; ...
'Scg2',	Neurons10,	's'; ...
'Scg5',	Neurons10,	'd'; ...
'Scn1b',	Neurons10,	'>'; ...
'Sdk2',	Neurons10,	'v'; ...
'Sepw1',	Neurons10,	'<'; ...
'Serpinb1b',	Neurons10,	'^'; ...
'Shisa8',	Neurons10,	'p'; ...
'Six3',	Neurons10,	'h'; ...
'Sla',	Immune,	'x'; ...
'Slc17a6',	Neurons11,	'*'; ...
'Slc17a7',	Neurons11,	'.'; ...
'Slc1a2',	Astrocytes,	'h'; ...
'Slc32a1',	Neurons11,	'+'; ...
'Slc6a11',	Astrocytes1,	'*'; ...
'Slc6a17',	Neurons11,	'x'; ...
'Slc6a2',	Neurons11,	'o'; ...
'Slc6a5',	Neurons11,	's'; ...
'Slco5a1',	Neurons11,	'd'; ...
'Sncb',	Neurons11,	'>'; ...
'Snhg11',	Neurons11,	'v'; ...
'Sp9',	Neurons11,	'<'; ...
'Sparc',	Vascular1,	'h'; ...
'Sparcl1',	Astrocytes1,	'.'; ...
'Spp1',	Vascular2,	'*'; ...
'Spp2',	Ependymal2,	'x'; ...
'Syndig1',	Neurons11,	'^'; ...
'Syt2',	Neurons11,	'p'; ...
'Syt4',	Neurons11,	'h'; ...
'Tcap',	Neurons12,	'*'; ...
'Tcf4',	Oligos,	'p'; ...
'Tcf7l2',	Oligos,	'h'; ...
'Tecr',	Neurons12,	'.'; ...
'Tfap2b',	Neurons12,	'+'; ...
'Thy1',	Neurons12,	'x'; ...
'Tlx3',	Neurons12,	'o'; ...
'Tmsb4x',	Vascular2,	'.'; ...
'Tph2',	Neurons12,	's'; ...
'Trh',	Neurons12,	'd'; ...
'Tshz1',	Neurons12,	'>'; ...
'Tshz2',	Neurons12,	'v'; ...
'Ttr',	Ependymal2,	'o'; ...
'Tuba1a',	Neurons12,	'<'; ...
'Ubb',	Neurons12,	'^'; ...
'Ube2c',	Oligos1,	'*'; ...
'Uncx',	Neurons12,	'p'; ...
'Vamp1',	Neurons12,	'h'; ...
'Vgf',	Neurons13,	'*'; ...
'Vsnl1',	Neurons13,	'.'; ...
'Vstm2b',	Neurons13,	'+'; ...
'Vtn',	Vascular2,	'+'; ...
'Xist',	Oligos1,	'.'; ...
'Zbtb20',	Ependymal2,	's'; ...
'Zeb2',	Oligos1,	'+'; ...
'Zic1',	Vascular2,	'x'; ...
    
    };

% delete any existing legend
fc = get(gcf, 'Children');
for i=1:length(fc)
    if strcmp(get(fc(i), 'UserData'), 'key')
        delete(fc(i));
    end
end

MainAxes = gca;

n =  size(New_symbols,1);

gc = get(MainAxes, 'children');
MyChildren = [];
for i=1:length(gc)
    if (strcmp(gc(i).Type, 'line') || strcmp(gc(i).Type, 'scatter')) ...
            && ~isempty(gc(i).DisplayName)
        MyChildren = [MyChildren; i];
    end
end
DisplayNames = {gc(MyChildren).DisplayName};
% get first word of display name as gene
GeneNames = cell(size(DisplayNames));
for i=1:length(DisplayNames)
    GeneNames{i} = strtok(DisplayNames{i});
end
    
clear h s;
j=1;
Present = [];
for i=1:n
    MyGeneName = New_symbols{i,1};
    l = find(strcmp(MyGeneName, GeneNames));
    if ~isempty(l)
        h(j) = gc(MyChildren(l));
		if strcmp(h(j).Type, 'line')
			set(h(j), 'Color', New_symbols{i,2});
        elseif strcmp(h(j).Type, 'scatter')
			set(h(j), 'CData', New_symbols{i,2});
		end
        set(h(j), 'Marker', New_symbols{i,3});

        if MarkerSize>0
			if strcmp(gc(l).Type, 'line')
				set(h(j), 'MarkerSize', MarkerSize);
			elseif strcmp(gc(l).Type, 'scatter')
				set(h(j), 'SizeData', MarkerSize);
			end
        end
        Present(j) = i;
        j=j+1;
    end
end

other_h = setdiff(gc(MyChildren), h);
other_symbols = {other_h.DisplayName};

all_h = [h(:); other_h(:)];
all_sym = {New_symbols{Present,1}, other_symbols{:}};

% lh = legend([h(:); other_h(:)], ...
%     {New_symbols{s,1}, other_symbols{:}}, ...
%     'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
% set(lh, 'color', 'k');
% 
% return;

if MultiCol==0
    lh = legend(all_h, all_sym, 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
    set(lh, 'color', 'k');
else
    ah = axes('Position', [.925 .13 .05 .8]);
    set(ah, 'color', 'k'); cla; hold on; box off
    set(ah, 'UserData', 'key');
    for j=1:length(Present)
        i = Present(j);
        plot(ceil(j/MultiCol)+.1, mod(j-1,MultiCol), New_symbols{i,3}, 'Color', New_symbols{i,2});
        text(ceil(j/MultiCol)+.3, mod(j-1,MultiCol), New_symbols{i,1}, 'color', 'w', 'fontsize', FontSize);
    end
    ylim([-1 MultiCol]);
    set(ah, 'xtick', []);
    set(ah, 'ytick', []);
    set(ah, 'ydir', 'reverse');
end
%     for c=1:nCols
%         rr=((c-1)*50 + 1):min(c*50, length(all_h));
%         if c==1
%             ah(c) = gca;
%             lh(c) = legend(all_h(rr), all_sym(rr), 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize, 'location', 'east');
%             set(lh(c), 'color', 'k');
%             pos(c,:) = get(lh(c), 'position');
%         else
%             ah(c) = axes('position',get(gca,'position'), 'visible','off');
%             lh(c) = legend(ah(c), all_h(rr), all_sym(rr), 'color', 'k', 'textcolor', 'w', 'fontsize', FontSize, 'location', 'east');
%             set(lh(c), 'position', pos(c-1,:) + [1.1 0 0 0]*pos(c-1,3));
%             uistack(lh(c), 'top');
%         end
%     end
%     axes(ah(1));
    
%    error('multicolumn not done yet!');
% end
%     for i=1:nCols
%         first = 1+(i-1)*nCols;
%         last = min(i*nCols,length(all_h));
%         lh = legend(all_h(first:last), ...
%             all_sym{first:last});%, ...
%             %'color', 'k', 'textcolor', 'w', 'fontsize', FontSize);
%         set(lh, 'color', 'k');
%     end
set(gcf, 'color', 'k');
set(gcf, 'InvertHardcopy', 'off');
    
axes(MainAxes)
uistack(ah, 'top');

end